In [ ]:
#version 1.0
from pyautogui import *
import pyautogui
import time
import keyboard
import random
import win32api, win32con
import numpy as np 
import os
from IPython.display import clear_output

def pri():
    a=r
    print(np.flipud(a)) 
        
def win():
    if r[0][0]==1:
        print("win")

def play():
    
        
        pos=int(input())
        clear_output(wait=True)
        
    
        if pos==1:
            r[0][0]=ans
            pri()
        if pos==2:
            r[0][1]=ans
            pri()
        if pos==3:
            r[0][2]=ans
            pri()
        if pos==4:
            r[1][0]=ans
            pri()
        if pos==5:
            r[1][1]=ans
            pri()
        if pos==6:
            r[1][2]=ans
            pri()
        if pos==7:
            r[2][0]=ans
            pri()
        if pos==8:
            r[2][1]=ans
            pri()
        if pos==9:
            r[2][2]=ans
            pri()

def checkwin(flag):
    if r[2][2]==r[1][1] and r[1][1]==r[0][0] and r[1][1]!=0:
        print("player ",ans," you won")
        return(0)
    if r[0][2]==r[1][1] and r[1][1]==r[2][0]and r[1][1]!=0:
        print("player ",ans," you won")
        return(0)
    
    if r[0][0]==r[1][0] and r[1][0]==r[2][0] and r[1][0]!=0:
        print("player ",ans," you won")
        return(0)
    if r[0][1]==r[1][1] and r[1][1]==r[2][1]and r[1][1]!=0:
        print("player ",ans," you won")
        return(0)
    if r[0][2]==r[1][2] and r[1][2]==r[2][2]and r[1][2]!=0:
        print("player ",ans," you won")
        return(0)
    
    if r[0][0]==r[0][1] and r[0][1]==r[0][2]and r[0][1]!=0:
        print("player ",ans," you won")
        return(0)
    if r[1][0]==r[1][1] and r[1][1]==r[1][2]and r[1][1]!=0:
        print("player ",ans," you won")
        return(0)
    if r[2][0]==r[2][1] and r[2][1]==r[2][2]and r[2][1]!=0:
        print("player ",ans," you won")
        return(0)
    else:
        return(1)
    


r = [[0,0,0],
     [0,0,0],
     [0,0,0]]
flag=1
ans=1
win=False
i=0
pri()
while i<9 and flag==1 :
    clear_output(wait=True)
    play()
    flag=checkwin(flag)
    if ans==1:
        ans=2
    else:
        ans=1
    
    i=i+1



In [ ]:
#version 2.0 player 2 genrates random inputs
from pyautogui import *
import pyautogui
import time
import keyboard
import random
import win32api, win32con
import numpy as np 
import os
import random
from IPython.display import clear_output

def pri():
    a=r
    print(np.flipud(a)) 
        
def win():
    if r[0][0]==1:
        print("win")

def play():
        pri()
        if ans==1:
            pos=int(input())
            if pos in flush:
                play()
            numberList.remove(pos)
            clear_output(wait=True)
        
        if ans==2:
            
            po = random.choices(numberList)
            pos=po[0]
            if pos in flush:
                play()
            
            numberList.remove(pos)
            print( numberList)
            
            
        flush.append(pos)
        if pos==1:
            r[0][0]=ans
            pri()
        if pos==2:
            r[0][1]=ans
            pri()
        if pos==3:
            r[0][2]=ans
            pri()
        if pos==4:
            r[1][0]=ans
            pri()
        if pos==5:
            r[1][1]=ans
            pri()
        if pos==6:
            r[1][2]=ans
            pri()
        if pos==7:
            r[2][0]=ans
            pri()
        if pos==8:
            r[2][1]=ans
            pri()
        if pos==9:
            r[2][2]=ans
            pri()

def checkwin(flag):
    if r[2][2]==r[1][1] and r[1][1]==r[0][0] and r[1][1]!=0:
        print("player ",ans," you won")
        return(0)
    if r[0][2]==r[1][1] and r[1][1]==r[2][0]and r[1][1]!=0:
        print("player ",ans," you won")
        return(0)
    
    if r[0][0]==r[1][0] and r[1][0]==r[2][0] and r[1][0]!=0:
        print("player ",ans," you won")
        return(0)
    if r[0][1]==r[1][1] and r[1][1]==r[2][1]and r[1][1]!=0:
        print("player ",ans," you won")
        return(0)
    if r[0][2]==r[1][2] and r[1][2]==r[2][2]and r[1][2]!=0:
        print("player ",ans," you won")
        return(0)
    
    if r[0][0]==r[0][1] and r[0][1]==r[0][2]and r[0][1]!=0:
        print("player ",ans," you won")
        return(0)
    if r[1][0]==r[1][1] and r[1][1]==r[1][2]and r[1][1]!=0:
        print("player ",ans," you won")
        return(0)
    if r[2][0]==r[2][1] and r[2][1]==r[2][2]and r[2][1]!=0:
        print("player ",ans," you won")
        return(0)
    else:
        return(1)
    


r = [[0,0,0],
     [0,0,0],
     [0,0,0]]
flag=1
ans=1
win=False
i=0
numberList = [1,2,3,4,5,6,7,8,9]
pri()
flush=[]
while i<9 and flag==1 :
    clear_output(wait=True)
    play()
    flag=checkwin(flag)
    if ans==1:
        ans=2
    else:
        ans=1
    
    i=i+1



[[2 0 0]
 [0 0 0]
 [1 0 0]]


In [4]:
qq=[1,2,3,4,5,6,7,8,9]
pos=9
qq.remove(pos)
print(qq)


[1, 2, 3, 4, 5, 6, 7, 8]
